### ISSUE TITLE
Questions about BabynameFileNotFoundException in babyname_parser.py

### ISSUE THREAD

**Issue by yeppin** [swsnu/swppfall2021#24]
I have a question about BabynameFileNotFoundException in babyname_parser.py file.(HW1)

After applying decorated function check_file_name_existence with inner function try_check_filename, there comes a prior error before BabynameFileNotFoundException is raised. And the sentence "During handling of the above exception, another exception occurred:" appears with the exception.
Is it okay since it raised the right exception anyway or should I also handle the prior error?

I'm looking forward to your reply, thank you.
```
parser = BabynameParser("/home/yebin/Desktop/SSPP/swpp-hw1-yeppin/babydata", 1900)
Traceback (most recent call last):
  File "/home/yebin/Desktop/SSPP/swpp-hw1-yeppin/babyname_parser.py", line 40, in try_check_filename
    func(a,b,c)
  File "/home/yebin/Desktop/SSPP/swpp-hw1-yeppin/babyname_parser.py", line 64, in __init__
    f = open('{0}/{1}.html'.format(self.dirname,self.year),'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/yebin/Desktop/SSPP/swpp-hw1-yeppin/babydata/1900.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yebin/Desktop/SSPP/swpp-hw1-yeppin/babyname_parser.py", line 44, in try_check_filename
    raise BabynameFileNotFoundException("No such file: {}".format(filename))
babyname_parser.BabynameFileNotFoundException: No such file: /home/yebin/Desktop/SSPP/swpp-hw1-yeppin/babydata/1900.html
```

**Comment by kdh0102** [comment]
It is OK as long as your program raises BabyFetchException.

Please check the related issue and the comment here:
https://github.com/swsnu/swppfall2021/issues/16#issuecomment-914322380
